/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/conversation`; params?: Router.UnknownInputParams; } | { pathname: `/grammar`; params?: Router.UnknownInputParams; } | { pathname: `/learning/flashcard`; params?: Router.UnknownInputParams; } | { pathname: `/learning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pronunciation`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/vocabulary`; params?: Router.UnknownInputParams; } | { pathname: `/grammar/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocabulary/word/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/achievements`; params?: Router.UnknownOutputParams; } | { pathname: `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/conversation`; params?: Router.UnknownOutputParams; } | { pathname: `/grammar`; params?: Router.UnknownOutputParams; } | { pathname: `/learning/flashcard`; params?: Router.UnknownOutputParams; } | { pathname: `/learning`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/pronunciation`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/vocabulary`; params?: Router.UnknownOutputParams; } | { pathname: `/grammar/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vocabulary/word/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/practice${`?${string}` | `#${string}` | ''}` | `/practice${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/achievements${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `/conversation${`?${string}` | `#${string}` | ''}` | `/grammar${`?${string}` | `#${string}` | ''}` | `/learning/flashcard${`?${string}` | `#${string}` | ''}` | `/learning${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/pronunciation${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/vocabulary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/conversation`; params?: Router.UnknownInputParams; } | { pathname: `/grammar`; params?: Router.UnknownInputParams; } | { pathname: `/learning/flashcard`; params?: Router.UnknownInputParams; } | { pathname: `/learning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pronunciation`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/vocabulary`; params?: Router.UnknownInputParams; } | `/grammar/${Router.SingleRoutePart<T>}` | `/vocabulary/word/${Router.SingleRoutePart<T>}` | { pathname: `/grammar/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocabulary/word/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
